In [19]:
import tensorflow as tf
import numpy as np

def generate_economic_parameters(B, N, M):
    valuations = tf.random.uniform((B, N, M), minval=0, maxval=1)

    return valuations

economic_parameters = generate_economic_parameters(10, 3, 3)
print(economic_parameters[7:10, :, :])

tf.Tensor(
[[[0.28156865 0.6199906  0.84128416]
  [0.89684653 0.88453555 0.99479485]
  [0.8649876  0.9553312  0.97638714]]

 [[0.3217517  0.47826588 0.8154495 ]
  [0.2698319  0.6477879  0.2473247 ]
  [0.3891294  0.5669074  0.55988264]]

 [[0.5293404  0.38335586 0.29942834]
  [0.50998867 0.512084   0.5605147 ]
  [0.20228052 0.97453606 0.22587669]]], shape=(3, 3, 3), dtype=float32)
